name: Deploy to Server

on:
  push:
    branches: [ main ]  # Trigger on push to main branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Replace with appropriate runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Add SSH key (encrypted)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0  # Install this action if needed
        with:
          host: ${{ secrets.SERVER_IP }}  # Replace with server IP
          username: ${{ secrets.SERVER_USER }}  # Replace with server username
          port: 22  # Default SSH port
          script: |
            cd /var/www/testingserver  # Change to deployment directory
            rsync -avz --delete-after $GITHUB_WORKSPACE/ .  # Sync files from GitHub workspace to server

