name: Sync with Remote Server

on:
  push:
    branches:
      - main

jobs:
  rsync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 172.21.1.91 >> ~/.ssh/known_hosts
          
      - name: Sync with Remote Server
        run: |
          rsync -avz --exclude='.git/' ./ root@172.21.1.91:/var/www/testingserver/
