name: Sync with Remote Server

on:
  push:
    branches:
      - main

jobs:
  rsync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Sync with Remote Server
        run: |
          rsync -avz -e 'ssh -i ${{ secrets.SSH_PRIVATE_KEY }}' --exclude='.git/' ./ root@172.21.1.91:/var/www/testingserver/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

