name: Deploy to Server

on:
  push:
    branches: [ main ]  # Trigger on push to main branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Replace with appropriate runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Add SSH key (encrypted)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | ssh-keygen id_rsa <<< "$SSH_PRIVATE_KEY"
          chmod 600 id_rsa

      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0  # Install this action if needed
        with:
          host: ${{ secrets.SERVER_IP }}  # Replace with server IP
          username: ${{ secrets.SERVER_USER }}  # Replace with server username
          port: 22  # Default SSH port
          script: |
            # Replace these commands with your deployment script
            rsync -avz -e "ssh -i id_rsa" ./ server_user@server_ip:/var/www/testingserver


