name: Sync Repository to Remote Server

on:
  push:
    branches:
      - main  # Change this to match your repository's main branch

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > /home/ubuntu/actions-runner/_work/testingserver/testingserver/.ssh/id_rsa && chmod 600 /home/ubuntu/actions-runner/_work/testingserver/testingserver/.ssh/id_rsa
        
      - name: Sync repository to remote server
        run: |
          rsync -avz --delete -e 'ssh -i /home/ubuntu/actions-runner/_work/testingserver/testingserver/.ssh/id_rsa -o StrictHostKeyChecking=no' ./ root@172.21.1.91:/var/www/html
