name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 172.21.1.91 >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@172.21.1.91 'sudo mkdir -p /var/www/html/go'
