name: 'Node CI'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Git Pull from Main
      run: git pull origin main -f

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
        ARGS: '-rlgoDzvc -i'
        SOURCE: 'dist/'
        REMOTE_HOST: '${{ secrets.REMOTE_HOST }}'
        REMOTE_USER: '${{ secrets.REMOTE_USER }}'
        REMOTE_PORT: '${{ secrets.REMOTE_PORT }}'
        EXCLUDE: '/dist/, /node_modules/'


        
