name: Check Editors Availability

on:
  push:
    branches:
      - main

jobs:
  check-node:
    runs-on: ubuntu-latest
    steps:
      - name: Check Node.js availability
        run: |
          node --version >/dev/null 2>&1 && echo "Node.js is installed at $(which node)" || echo "Node.js is not installed"
