name: 'Node CI'

on:
  - 'push'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Deploy to Staging server'
      uses: 'easingthemes/ssh-deploy@main'
      with:
        SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
        ARGS: '-rlgoDzvc -i'
        SOURCE: 'dist/'
        REMOTE_HOST: '${{ secrets.REMOTE_HOST }}'
        REMOTE_USER: '${{ secrets.REMOTE_USER }}'
        REMOTE_PORT: '${{ secrets.REMOTE_PORT }}'
        EXCLUDE: '/dist/, /node_modules/'
        SCRIPT_BEFORE: |
          echo "Running before deployment script:"
          whoami
          ls -al
        SCRIPT_AFTER: |
          echo "Running after deployment script:"
          whoami
          ls -al
          echo $RSYNC_STDOUT
