name: Check Editors Availability

on:
  push:
    branches:
      - main

jobs:
  check_editors:
    runs-on: ubuntu-latest

    steps:
      - name: Check if vi is installed
        run: |
          command -v vi && echo "vi installed" || echo "vi not installed"

      - name: Check if nano is installed
        run: |
          command -v nano && echo "nano installed" || echo "nano not installed"
