name: Simple Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to /var/www/html
        run: |
          rsync -avz --delete ./ new/sam
