name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an appropriate runner based on your requirements

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install rsync -y  # Install rsync on the runner

      - name: Sync repository with remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          rsync -e "ssh -p 7102" -avz --delete ./ root@172.21.1.91:/var/www/testingserver/
