name: Display SSH private key

on:
  push:
    branches:
      - main

jobs:
  display_key:
    runs-on: ubuntu-latest
    steps:
      - name: Display SSH private key
        run: |
          echo '${{ secrets.SSH_PRIVATE_KEY }}'
