name: Create Directory on Remote Server

on:
  push:
    branches:
      - main

jobs:
  create_directory:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Remote Server and Create Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh -v -i ${{ secrets.SSH_PRIVATE_KEY }} -p ${{ secrets.PORT }} ${secrets.USERNAME}@${secrets.HOST} "cd /var/www/testingserver/ && mkdir go"
