name: Update Remote Server

on:
  push:
    branches:
      - main

jobs:
  update-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Push code to remote server
        run: |
          ssh root@172.21.1.91 'cd /var/www/testingserver/ && git pull origin main -f'
