name: Sync Git Workspace with Testing Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Sync Git Workspace with Testing Server
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync --timeout=60 -avz -e "ssh -p ${{ secrets.PORT }}" $GITWORKSPACE/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/testingserver/
      env:
        GITWORKSPACE: ${{ github.workspace }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

