name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an appropriate runner based on your requirements

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install rsync -y  # Install rsync on the runner

      - name: Sync repository with remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add your remote server to known_hosts
          ssh-keyscan -p 7102 -H 172.21.1.91 >> ~/.ssh/known_hosts
          # Perform rsync to sync the repository with the remote server
          rsync -e "ssh -p 7102" -avz --delete ./ root@172.21.1.91:/var/www/testingserver/
