name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: |
          rsync -avz -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY }}" --exclude='.git/' ./ root@${{ secrets.HOST }}:/var/www/testingserver/
