name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update known_hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H 13.49.230.188 >> ~/.ssh/known_hosts

      - name: Deploy to Stage
        run: |
          rsync -r --delete-after $GITHUB_WORKSPACE/ -e "ssh -i $HOME/.ssh/id_rsa" ubuntu@ec2-13-49-230-188.eu-north-1.compute.amazonaws.com:/home/ubuntu/stage/
      
