name: Output SSH Private Key

on:
  push:
    branches: [main]  # Trigger on push to main branch (adjust as needed)

jobs:
  output_ssh_key:
    runs-on: ubuntu-latest  # Replace with appropriate runner

    steps:
      - name: Output SSH Private Key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"
