name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log repository contents
      run: ls -l $GITHUB_WORKSPACE

    - name: Install rsync
      run: sudo apt-get install rsync -y

    - name: Deploy to server
      run: |
        rsync -avz --delete -e "ssh -p 7102" $GITHUB_WORKSPACE/ root@172.21.1.91:/var/www/testingserver/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
