name: Create SSH Key File

on:
  push:
    branches: [main]  # Trigger on push to main branch (adjust as needed)

jobs:
  create_ssh_key_file:
    runs-on: ubuntu-latest  # Replace with appropriate runner

    steps:
      - name: Create SSH Key File
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        shell: bash

      - name: Display File Content
        run: cat private_key.pem

