name: Rsync to Server
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ssh-private-key: '${{ secrets.TEST_PRIVATE_KEY }}'
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
      - name: Rsync to Server
        run: >-
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i" ./ root@172.21.1.91:/var/www/git
